name: manage-azure-policy-d4c42558
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'ptest/policies/Network_interfaces_should_not_have_public_IPs_83a86a26-fd1f-447c-b59d-e51f44264114/**'
#      - 'ptest/policies/Public_IP_addresses_should_have_resource_logs_enabled_for_Azure_DDoS_Protection_Standard_752154a7-1e0f-45c6-a880-ac75a7e4f648/**'
#      - .github/workflows/manage-azure-policy-d4c42558.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_d4c42558}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          ptest/policies/Network_interfaces_should_not_have_public_IPs_83a86a26-fd1f-447c-b59d-e51f44264114/**
          ptest/policies/Public_IP_addresses_should_have_resource_logs_enabled_for_Azure_DDoS_Protection_Standard_752154a7-1e0f-45c6-a880-ac75a7e4f648/**
